### ISSUE TITLE
Does KITS2023 have patient JSON information like Kits19/21 did? 

### ISSUE THREAD

**Issue by ChrisJWest** [neheller/kits23#10]
Just wondering! I am interested in using the patient JSON information for some research, but I can't seem to find it in the Kits23 data directory (either on Github or after batch downloading). Stuff like demographic information and indicators for kidney function.

<img width="296" alt="image" src="https://github.com/neheller/kits23/assets/40185957/3220e3e4-d892-4cf5-90b1-9ffdba058f3c">

If not, please let me know if there is a way I could get a copy. Thanks!

**Comment by neheller** [comment]
Thanks for your interest in this aspect of the data! We're working on collecting the last of this information and hope to release it sometime next month.

**Comment by Neha-ksu** [comment]
I have same query, when could we expect the .json file?
