### ISSUE TITLE
Have not received the form that requires me to select the time to receive the test set.

### ISSUE THREAD

**Issue by lizflora** [neheller/kits23#11]
Hello, 
I have already submitted my short paper, but I have not received the form that requires me to select the time to receive the test set. Has it not been sent out yet or is there any other reason? By the way, could you please let me know the deadline for submitting the segmentation results?
 I look forward to your response. Thank you.

**Comment by neheller** [comment]
Our apologies for the delay! We hadn't planned to send the form link out until the deadline this Friday. If you'd like to submit the form early, you can find it [here](https://forms.gle/dw67F2oGZtCEJZXk6).

The deadline for submitting predictions will be 24 hours after the time that you elect to receive the test images. The soonest possible is July 21 and the latest is July 27.
