### ISSUE TITLE
got this error

### ISSUE THREAD

**Issue by Neha-ksu** [neheller/kits23#2]
<img width="1095" alt="Screenshot 2023-04-15 at 9 02 33 PM" src="https://user-images.githubusercontent.com/81189994/232260605-4bac99e0-bb57-44fb-a824-c0eb24fbb6f4.png">

**Comment by neheller** [comment]
I think you need to use `%cd` rather than `!cd` in Jupyter. It's generally a good idea to use `%pip` rather than `!pip3` too.

![image](https://user-images.githubusercontent.com/10672754/233205464-e6ead318-aac9-487e-9f6d-671249305a17.png)

**Comment by neheller** [comment]
Did this solve your problem @Neha-ksu?

**Comment by neheller** [comment]
Closing for now. Feel free to reopen if you're still having issues.
