### ISSUE TITLE
hi Json file is not given on clinical records

### ISSUE THREAD

**Issue by kirangpcet** [neheller/kits23#4]
hi Json file is not given on clinical records

**Comment by neheller** [comment]
Sorry for the delay on that. We're working on it and should have it ready in the coming weeks.

**Comment by zbwlzu** [comment]
hi, when will the json file be uploaded?

**Comment by neheller** [comment]
Sorry it's taking longer than expected. We should have it ready before MICCAI in October.

**Comment by neheller** [comment]
Apologies for the long delay. [The clinical data](https://github.com/neheller/kits23/blob/main/dataset/kits23.json) has now been released.
