### ISSUE TITLE
Some cases do not have segmentation file

### ISSUE THREAD

**Issue by mohamedelhacen** [neheller/kits23#5]
In some cases there is no segmentation file. Does this mean that their is no kidneys in this images or they are just not labeled?

**Comment by neheller** [comment]
Every case should have a `segmentation.nii.gz` file. Which cases are you seeing without them? Perhaps your clone didn't run to completion?

**Comment by mohamedelhacen** [comment]
Thank you, it fixed. The problem was in the cloning of the repository.
